% requires 'crops' directory generated by cropper.m
% and 'masks' directory (edited version of 'rawMasks' generated by cropper.m)

% copy cropped directory
dirCH = '../character';
if exist(dirCH, 'dir')
    rmdir(dirCH, 's');
end
mkdir(dirCH);

% for each base character folder
characters = dir('crop');
N = length(characters);
for n = 1:N
    fighter = characters(n);
    if fighter.isdir
        dirFI = [dirCH, '/', fighter.name];
        mkdir(dirFI);
        variants = dir([fighter.folder, '/', fighter.name]);
        M = length(variants);
        for m = 1:M
            variant = variants(m);
            if contains(variant.name, '.png')
                im = imread([variant.folder, '/', variant.name]);
                shadow = imread(['shadow/', fighter.name, '.png']);
                mask = imread(['mask/', fighter.name, '.png']);
                imwrite(im .* (mask/256), [dirFI, '/', variant.name], 'Alpha', shadow);
            end
        end
    end
end
