% requires 'crops' directory generated by cropper.m
% and 'masks' directory (edited version of 'rawMasks' generated by cropper.m)

% copy cropped directory
if exist('../characters', 'dir')
    rmdir('../characters', 's');
end
copyfile('crops', '../characters');

% for each base character folder
characters = dir('masks');
N = length(characters);
for n = 1:N
    character = characters(n);
    if contains(character.name, '.png')
        variants = dir(['../characters/', erase(character.name, '.png')]);
        M = length(variants);
        for m = 1:M
            variant = variants(m);
            if contains(variant.name, '.png')
                im = imread([variant.folder, '/', variant.name]);
                mask = imread([character.folder, '/', character.name]);
                imwrite(im, [variant.folder, '/', variant.name], 'Alpha', mask);
            end
        end
    end
end
